---
- name: Creacion de instancia de prueba
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: ansible-vm1
       image: "cirros"
       key_name: octavia-ssh-key
       timeout: 200
       flavor: m1.tiny
       auto_ip: no
       network: 838f6119-b2c2-460c-a830-b78c89d94c8a
       security_groups: default
       meta:
         os: ubuntu
