---
- name: Creacion de instancia de prueba
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       validate_certs: no
       state: present
       name: ansible-vm1
       image: "cirros"
       key_name: octavia-ssh-key
       timeout: 200
       flavor: m1.tiny
       auto_ip: no
       network: e61a10ac-874e-4ef9-a4cb-53346b74be27
       security_groups: default
       meta:
         os: cirros
     auth:
       project_name: Redhat_jmanuel
